disabled_rules: # rule identifiers to exclude from running
  - todo
  - unused_closure_parameter
  - file_length
opt_in_rules: # some rules are only opt-in
  # - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - .
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 160 #120
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
function_body_length:
  - 60
type_name:
  min_length: 1 #4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  allowed_symbols: "_"
  min_length: # only min_length
    warning: 1
    error: 1 #4 # only error
  max_length:
    warning: 50
    error: 50
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
function_parameter_count: 6
large_tuple: 3
cyclomatic_complexity:
  ignores_case_statements: true
